function applyFigureStyle(axHandle)
% applyFigureStyle  统一设置报告图表的白底黑字样式。

    if nargin < 1
        axHandle = gca;
    end

    figHandle = ancestor(axHandle, 'figure');
    set(figHandle, 'Color', 'w', 'Position', [100, 100, 800, 600], ...
        'InvertHardcopy', 'off');
    set(axHandle, ...
        'Color', 'w', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'GridColor', [0.70, 0.70, 0.70], ...
        'MinorGridColor', [0.85, 0.85, 0.85], ...
        'FontName', '宋体', ...
        'FontSize', 11, ...
        'LineWidth', 1.0, ...
        'Box', 'on', ...
        'Layer', 'top');
    set(get(axHandle, 'Title'), 'Color', 'k');
    set(get(axHandle, 'XLabel'), 'Color', 'k');
    set(get(axHandle, 'YLabel'), 'Color', 'k');
    legendHandle = findobj(figHandle, 'Type', 'legend');
    if ~isempty(legendHandle)
        set(legendHandle, 'Color', 'w', 'TextColor', 'k', ...
            'EdgeColor', [0.60, 0.60, 0.60]);
    end
    grid(axHandle, 'on');
end
